@base= http://localhost:3000




POST {{base}}/auth/register
Content-Type: application/json

{
    "email" : "eddine@nasa.ca", 
    "pseudo":"eddine123",
    "password":"apollo123"
}

###
# @name login
POST {{base}}/auth/login
Content-Type: application/json

{
    "email":"eddine@nasa.ca",
    "password":"apollo123"
}


###
GET {{base}}/auth/me 
Authorization: Bearer {{login.response.body.token}}

###
POST {{base}}/lancement/importer
Content-Type:  application/json 

{"limite": 10}



###
GET {{base}}/lancement